<?php
return [
    'adminEmail' => 'admin@example.com',
    'fromEmail' => '',

    "positiveValues"=>["yes","Yes","YES","true","TRUE", "True",1],
    "negativeValues"=>["no","No","NO","false","FALSE", "False",0],

    'lead-prefix' => 'L',
    'lead-sufix' => date('Y'),

    'document.status' => [
        'offer_approved' => Yii::t('app', 'Offer approved, waiting to sent'),
        'offer_canceled' => Yii::t('app', 'Offer canceled'),
        'offer_hold' => Yii::t('app', 'Offer on hold'),
        'offer_waiting' => Yii::t('app', 'Offer waiting for approval'),
        'offer_completed' => Yii::t('app', 'Offer completed'),
        'order_new' => Yii::t('app', 'New order'),
        'order_sent' => Yii::t('app', 'Order send'),
        'order_hold' => Yii::t('app', 'Order waiting start date'),
        'order_rejected' => Yii::t('app', 'Order rejected'),
        'order_done' => Yii::t('app', 'Order done'),
        'order_completed' => Yii::t('app', 'Order completed'),
        'order_ready_for_invoice' => Yii::t('app', 'Ready for invoice'),
        'estimate_approved' => Yii::t('app', 'Estimate approved, waiting to sent'),
        'estimate_hold' => Yii::t('app', 'Estimate waiting work intake date'),
        'estimate_completed'=>Yii::t('app','Estimate completed'),
        'estimate_canceled'=>Yii::t('app','Estimate canceled'),
        'waiting' => Yii::t('app', 'Waiting for approval manager'),
        'lead_waiting'=>Yii::t('app','Partner request'),
        'estimate_waiting'=>Yii::t('app','Estimate waiting for approval'),
        'estimate_waiting_partner'=>Yii::t('app','Estimate waiting for partner'),
        'lead_approved' => Yii::t('app', 'Lead created'),
        'hold' => Yii::t('app', 'On hold'),
        'completed' => Yii::t('app', 'Completed'),
        'closed' => Yii::t('app', 'Closed'),
        'lead_partially_completed' => Yii::t('app', 'Multiple requests'),
        'rejected' => Yii::t('app', 'Rejected'),
        'lead_rejected'=>Yii::t('app','Lead cancelled'),
        'lead_hold'=>Yii::t('app','Lead on hold'),
        'lead_completed'=>Yii::t('app','Lead completed'),
        'lead_closed'=>Yii::t('app','Lead closed'),
        'canceled' => Yii::t('app', 'Canceled'),
        'offer_sent' => Yii::t('app', 'Offer sent, waiting for confirmation'),
        'offer_accepted' => Yii::t('app', 'Offer accepted, waiting for order'),
        'offer_rejected' => Yii::t('app', 'Offer rejected'),
        'accepted' => Yii::t('app', 'Accepted'),
        'new' => Yii::t('app', 'New'),
        'bill_new'=>Yii::t('app','Ready for invoice'),
        'done' => Yii::t('app', 'Order done'),
        'sent' => Yii::t('app', 'Order sent to partner'),
        'ready_for_invoice'=>Yii::t('app', 'Ready for invoice'),
        'bill_sent' => Yii::t('app', 'Invoice send'),
        'bill_started_paying' => Yii::t('app', 'Start payment'),
        'bill_partial_paid' => Yii::t('app', 'Partial payment'),
        'bill_paid' => Yii::t('app', 'Complete payment'),
        'bill_start_partial'=>Yii::t('app', 'Start payment-Partial payment'),
        'bill_complete_partial'=>Yii::t('app', 'Complete payment-Partial payment'),
        'offer_accepted_part_payment'=>Yii::t('app', 'Offer accepted, waiting for part-payment'),
        'first_payment_done'=>Yii::t('app', 'Offer part-payment done'),
        'offer_change'=>Yii::t('app', 'Offer change'),
    ],

    'user.roles' => [
        'sysadmin' => 'sysadmin',
        'admin' => 'admin',
        'estimate_creator' => 'estimate_creator',
        'offer_creator' => 'offer_creator',
        'order_creator' => 'order_creator',
        'bill_creator' => 'bill_creator',
        'project_approval' => 'project_approval',
        'order_manager' => 'order_manager',
        'bill_manager' => 'bill_manager',
        'general_manager' => 'general_manager',
        'manager' => 'manager'
    ],
    
    'insertionValues' => [
        "'s",
        "'t",
        "a",
        "aan",
        "aan 't",
        "aan de",
        "aan den",
        "aan der",
        "aan het",
        "aan t",
        "af",
        "al",
        "am",
        "am de",
        "auf",
        "auf dem",
        "auf den",
        "auf der",
        "auf ter",
        "aus",
        "aus 'm",
        "aus dem",
        "aus den",
        "aus der",
        "aus m",
        "ben",
        "bij",
        "bij 't",
        "bij de",
        "bij den",
        "bij het",
        "bij t",
        "bin",
        "boven d",
        "boven d’",
        "d",
        "d’",
        "da",
        "dal",
        "dal’",
        "dalla",
        "das",
        "de",
        "de die",
        "de die le",
        "de l",
        "de l’",
        "de la",
        "de las",
        "de le",
        "de van der",
        "deca",
        "degli",
        "dei",
        "del",
        "della",
        "den",
        "der",
        "des",
        "di",
        "die le",
        "do",
        "don",
        "dos",
        "du",
        "el",
        "het",
        "i",
        "im",
        "in",
        "in 't",
        "in de",
        "in den",
        "in der",
        "in het",
        "in t",
        "l",
        "l’",
        "la",
        "las",
        "le",
        "les",
        "lo",
        "los",
        "of",
        "onder",
        "onder 't",
        "onder de",
        "onder den",
        "onder het",
        "onder t",
        "op",
        "op 't",
        "op de",
        "op den",
        "op der",
        "op gen",
        "op het",
        "op t",
        "op ten",
        "over",
        "over 't",
        "over de",
        "over den",
        "over het",
        "over t",
        "s",
        "s’",
        "t",
        "te",
        "ten",
        "ter",
        "tho",
        "thoe",
        "thor",
        "to",
        "toe",
        "tot",
        "uijt",
        "uijt 't",
        "uijt de",
        "uijt den",
        "uijt te de",
        "uijt ten",
        "uit",
        "uit 't",
        "uit de",
        "uit den",
        "uit het",
        "uit t",
        "uit te de",
        "uit ten",
        "unter",
        "van",
        "van 't",
        "van de",
        "van de l",
        "van de l’",
        "van den",
        "van der",
        "van gen",
        "van het",
        "van la",
        "van t",
        "van ter",
        "van van de",
        "ver",
        "vom",
        "von",
        "von 't",
        "von dem",
        "von den",
        "von der",
        "von t",
        "voor",
        "voor 't",
        "voor de",
        "voor den",
        "voor in 't",
        "voor in t",
        "vor",
        "vor der",
        "zu",
        "zum",
        "zur",
    ],

    'active'=>1,
    'disabled'=>3,
    'deleted'=>2,
    'not finished'=>5,
];
